org: saurabhlm10
app: self-invoke
service: self-invoke
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  collectPosts:
    handler: src/functions/collect-posts.function.handler
    events:
      - httpApi:
          path: /collectPosts/{page}
          method: get
  checkPagePostCollectionStatus:
    handler: src/functions/check-page-post-collection-status.function.handler
    events:
      - httpApi:
          path: /checkPagePostCollectionStatus/{page}
          method: get
