org: saurabhlm10
app: self-invoke
service: self-invoke
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  collectPosts:
    handler: src/functions/collect-posts.handler
    events:
      - httpApi:
          path: /collectPosts/{page}
          method: get
